version: '3.8'

services:
  living-research-intelligence:
    build: .
    container_name: research-intelligence-system
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - research-network
    volumes:
      # Optional: Mount config files if needed
      - ./config:/etc/nginx/conf.d:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.research-intelligence.rule=Host(`localhost`)"
      - "traefik.http.services.research-intelligence.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production deployments
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    networks:
      - research-network
    profiles:
      - production
    restart: unless-stopped

  # Optional: SSL certificate automation
  letsencrypt:
    image: nginxproxy/acme-companion:latest
    container_name: nginx-proxy-acme
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=your-email@example.com
    networks:
      - research-network
    profiles:
      - production
    restart: unless-stopped
    depends_on:
      - nginx-proxy

networks:
  research-network:
    driver: bridge
    name: research-intelligence-network

volumes:
  certs:
    name: nginx-certs
  vhost:
    name: nginx-vhost
  html:
    name: nginx-html
  acme:
    name: acme-data